---
- name: Ensure users exist
  ansible.builtin.user:
    name: "{{ item.name }}"
    shell: "{{ item.shell }}"
    state: present
  loop:
    - { name: "{{ users.user1.name }}", shell: "{{ users.user1.shell }}" }
    - { name: "{{ users.user2.name }}", shell: "{{ users.user2.shell }}" }

- name: Check if users file in sudoers.d folder exists
  ansible.builtin.stat:
    path: "{{ sudoers.file }}"
  register: sudoers_file

- name: Ensure users file in sudoers.d folder is created
  ansible.builtin.file:
    dest: "{{ sudoers.file }}"
    state: touch
    owner: root
    group: root
    mode: '0600'
  when: not sudoers_file.stat.exists

- name: Ensure users are in sudoers
  ansible.builtin.lineinfile:
    dest: "{{ sudoers.file }}"
    state: present
    regexp: '^{{ item.name }}'
    line: '{{ item.name }} ALL=(ALL) NOPASSWD: ALL'
    validate: 'visudo -cf %s'
  loop:
    - { name: "{{ users.user1.name }}" }
    - { name: "{{ users.user2.name }}" }
