---
- name: Ensure Zabbix GPG key is imported (RedHat)
  ansible.builtin.rpm_key:
    state: present
    key: https://repo.zabbix.com/zabbix-official-repo.key
  when: ansible_os_family == 'RedHat'

- name: Ensure Zabbix GPG key is imported (Debian)
  ansible.builtin.apt_key:
    url: https://repo.zabbix.com/zabbix-official-repo.key
    state: present
  when: ansible_os_family == 'Debian'

- name: Ensure Zabbix repo is added (RedHat)
  ansible.builtin.dnf:
    name: "{{ zabbix.repo_package_redhat }}"
    state: present
    update_cache: true
  when: ansible_os_family == 'RedHat'

- name: Ensure Zabbix repo is added (Debian)
  ansible.builtin.apt:
    deb: "{{ zabbix.repo_package_ubuntu }}"
    state: present
    update_cache: true
  when: ansible_os_family == 'Debian'

- name: Ensure Zabbix Agent 2 is installed
  ansible.builtin.package:
    name:
      - zabbix-agent2
      - zabbix-agent2-plugin-*
    state: present

- name: Ensure Zabbix Agent server is configured
  ansible.builtin.lineinfile:
    path: "{{ zabbix.agent2_conf }}"
    regexp: '^Server='
    line: Server={{ zabbix.server_fqdn }}
  notify: Restart Zabbix Agent

- name: Ensure Zabbix Agent server active is configured
  ansible.builtin.lineinfile:
    path: "{{ zabbix.agent2_conf }}"
    regexp: '^ServerActive='
    line: ServerActive={{ zabbix.server_fqdn }}
  notify: Restart Zabbix Agent

- name: Ensure Zabbix Agent hostname is configured
  ansible.builtin.lineinfile:
    path: "{{ zabbix.agent2_conf }}"
    regexp: '^Hostname='
    line: Hostname={{ inventory_hostname }}
  notify: Restart Zabbix Agent

- name: Ensure Zabbix Agent service is enabled and started
  ansible.builtin.service:
    name: zabbix-agent2
    enabled: true
    state: started
